### ISSUE TITLE
React v.18 support?

### ISSUE THREAD

**Issue by guilleigmu** [almond-bongbong/react-simple-toasts#22]
Hey guys. 

Congrats for this awesome little yet useful package.

I guess you already know, but currently the implementation is not supported by the newest version of React (>18.0.0). Every time the `toast` function is executed, this error prompts in the console:

![Captura de pantalla 2022-09-14 a las 12 42 44](https://user-images.githubusercontent.com/103815026/190133996-c7f4ee68-86db-47a7-9789-812572a09b92.png)

Any chance you are already working on a new workaround instead of using `ReactDOM.render`?

Thanks in advance!

**Comment by almond-bongbong** [comment]
We'll have an update ready right away. 

Thank you!

**Comment by almond-bongbong** [comment]
Updated for React v18
