### ISSUE TITLE
Can't use package out of the box: Import error

### ISSUE THREAD

**Issue by mnbucher** [almond-bongbong/react-simple-toasts#35]
After installing the module from npm, I get the following runtime exceptions:

`Module not found: Error: Can't resolve '/Users/cmlee/Code/react-simple-toasts/node_modules/tslib/tslib.es6.js'`

and

`Module not found: Error: Can't resolve '/Users/cmlee/Code/react-simple-toasts/node_modules/style-inject/dist/style-inject.es.js'`

I don't use Typescript for my React project. Following the path with the user 'cmlee', I suspect something has gone wrong on the export / building of the package, maybe only for non-TS users?

**Comment by almond-bongbong** [comment]
@mnbucher 
Thank you for your report.
We found a problem with the build setup and corrected it.
Can you try the 3.1.5 version?

thank you!
